### ISSUE TITLE
Support for nrf52840-dk

### ISSUE THREAD

**Issue by ia0** [nrf-rs/nrf52-dk#1]
Hi @Istar-Eldritch ,

I'm wondering if this repository is specific to the nrf52832-dk or if it could also be used for the nrf52840-dk too (e.g. using features to select the actual board).

Thanks!

**Comment by Yatekii** [comment]
The nRF52840-DK one is here: https://github.com/nrf-rs/nrf52840-dk:)

**Comment by ia0** [comment]
Thanks a lot! Yes that sounds exactly right. I couldn't find it.

Would it make sense to add both this crate as well as the nrf52840-dk one to https://github.com/rust-embedded/awesome-embedded-rust#nordic-2? I would expect people to search there first.

**Comment by ia0** [comment]
I created https://github.com/rust-embedded/awesome-embedded-rust/pull/347 for nrf52840-dk-bsp. I didn't create one for this crate because it doesn't look like it's on crates.io. I'm closing this issue since it is now fixed for me. Thanks for your help!
